In [1]:
# use if autocompletion is not working
%config Completer.use_jedi = False

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import os
import pandas as pd
import json
import numpy as np
from tqdm import tqdm

from fuzzywuzzy import fuzz

In [ ]:
from modern_slavery_registry import get_root_path

In [ ]:
PROJECT_PATH = get_root_path()
DATA_PATH = os.path.join(PROJECT_PATH, "data")

COMPANIES_JSON = "companies_060421.json"

In [ ]:
%%time
companies_info = ""
with open(os.path.join(PROJECT_PATH, DATA_PATH, COMPANIES_JSON),encoding='utf8') as f:
    for i, line in enumerate(f):
        companies_info += line
companies_info = companies_info.replace("\n", "")
companies_info = json.loads(companies_info)

In [ ]:
print(f"Number of companies: {len(companies_info)}")

In [ ]:
for i, (k,v) in enumerate(companies_info.items()):
    print(k, v)
    if i == 10: break 

In [9]:
companies = [info["company"].lower() for info in companies_info.values()]

In [10]:
len(np.unique(companies)), len(companies)

(19630, 19690)

In [11]:
statements = pd.read_excel(os.path.join(PROJECT_PATH, DATA_PATH, "sheets","subset_data.xlsx"))

In [12]:
statements.head()

URL  \
0  https://img1.wsimg.com/blobby/go/7695baff-3f0f...   
1  https://1spatial.com/who-we-are/legal/modern-s...   
2  https://www.shazans.com/slavery-and-human-traf...   
3  https://www.business-humanrights.org/sites/def...   
4  https://www.2agriculture.com/wp-content/upload...   

                           Company  \
0  "K" Line Holding Europe Limited   
1                     1Spatial Plc   
2              1Stop Halal Limited   
3       1st Step Solutions Limited   
4            2 Agriculture Limited   

                                     final_statement  \
0  66 99 “K” Line Holding (Europe) Limited kM K L...   
1  1Spatial Modern Slavery Act Policy Statement H...   
2  Slavery and Human Trafficking Statement – Shaz...   
3  7/28/2019 Modern Slavery Statement 2018 - 1st ...   
4  fh Modern Slavery Act 2015: slavery and human ...   

  years_with_and_without_act    years_with_act  \
0   ['2015', '2019', '2018']  ['2015', '2019']   
1                   ['2015']          ['2015']   
2   ['2015', '2019', '2018']  ['2015', '2018']   
3   ['2015', '2019', '2018']  ['2015', '2018']   
4   ['2015', '2019', '2018']  ['2015', '2018']   

                             final_statement_cleaned  \
0  66 99 km sh foor eum hold europe ltd 200 alder...   
1  home solution government boundary law enforcem...   
2  shazans shazan food continue monitor covid 19 ...   
3  28 2019 2018 statement make pursuant sec 54 20...   
4  fh 2015 introduction uk act require business s...   

   len(final_statement_cleaned)  
0                          1873  
1                          2128  
2                          1840  
3                          1843  
4                          1372

In [13]:
exact_match = [company for company in tqdm(statements["Company"], leave=False) if company.lower() in companies]

In [14]:
len(exact_match)

6910

In [15]:
fuzz.ratio("Catherine Gitau", "Catherine Gitau")

100

In [37]:
%%time
top_n = 5
top_n_ratio_match = []

for comp1 in tqdm(statements["Company"].values[:10], leave=False):
    ratio = np.argsort([fuzz.token_sort_ratio(comp1.lower(), comp2.lower()) for comp2 in companies])
    top_n_ratio_match.append(ratio[-top_n:][::-1])

Wall time: 4.17 s


In [38]:
top_n_ratio_match

[array([12277, 15487, 17836, 11022, 13248], dtype=int64),
 array([14583, 13037,  8502, 16521, 14422], dtype=int64),
 array([15309, 15492, 17539, 14395, 12640], dtype=int64),
 array([12137, 17479, 18811, 16598, 19090], dtype=int64),
 array([12902, 11978, 16619, 18271, 12865], dtype=int64),
 array([12902, 11978, 16619, 18271, 12865], dtype=int64),
 array([13849, 15279, 13106, 17404, 13971], dtype=int64),
 array([ 6912, 18366, 16836, 18668, 13660], dtype=int64),
 array([18080, 16445, 15679, 15549, 15713], dtype=int64),
 array([17225, 14099, 19532, 13915, 18194], dtype=int64)]

In [44]:
i = 9 
statements["Company"].values[i], [companies[j] for j in top_n_ratio_match[i]]

('2M Holdings Ltd',
 ['2m holdings ltd',
  'clinimed (holdings) ltd',
  'amita holdings co., ltd.',
  'amigo holdings limited',
  'bv holdings limited'])

In [30]:
len(statements)

9993

In [34]:

np.arange(10)[-5:]

array([5, 6, 7, 8, 9])

In [17]:
235 * 1e-3 * 10

2.35